### ISSUE TITLE
Site

### ISSUE THREAD

**Issue by danimesq** [ZeroCoinOrganization/Zerocoin-wallet#6]

**Comment by purplesyringa** [comment]
I think I can do this now -- maybe using Vue. Would you want to assign me to this issue?

**Comment by danimesq** [comment]
Sorry, but I prefer to do it myself (and to free up your efforts).

**Comment by purplesyringa** [comment]
Okay, I just wanted to say that if I want to start implementing JavaScript side of the blockchain, I'd like to have a site set up.

**Comment by danimesq** [comment]
> Okay, I just wanted to say that if I want to start implementing JavaScript side of the blockchain, I'd like to have a site set up.

The blockchain will not work on site, but in the Wallet (that is a merged site).
About the wallet I can sign you. But I'll also apply some designs on the wallet, then you can create just the basic skeleton.

I ask if I can assign you on those issues:

Blockchain using PeerMessage/BackgroundProccessing (#2)
Centralized emission (#3)
Genesis block (#4)
Transaction speed benchmark (#8)

?

**Comment by purplesyringa** [comment]
Assign me to all of the issues except #8, please. I'll check #8 later.

**Comment by purplesyringa** [comment]
What I meant is that I need to write JS code somewhere, but we haven't build any site yet, so I can't write any JS code. :(

**Comment by danimesq** [comment]
@imachug
Oh =/
I'll create the site today.

Is you open to create a Git plugin, for blockchain and archives?

**Comment by purplesyringa** [comment]
Err... Git plugin?

By the way, what's your `today` in UTC?

**Comment by danimesq** [comment]
> what's your today in UTC?

23:22

> Err... Git plugin?

https://github.com/ZeroCoinOrganization/Zerocoin-wallet/issues/4#issuecomment-421053539

**Comment by danimesq** [comment]
![znc](https://user-images.githubusercontent.com/6765277/45591309-8de00f00-b925-11e8-9af6-b1995157226e.png)

**Comment by danimesq** [comment]
@imachug 
http://127.0.0.1:43110/1ZNCyrnSdpws2rruHVy3fTRKfnmd1RMgH

**Comment by purplesyringa** [comment]
Thank you. Is there a repository for this site somewhere?

**Comment by purplesyringa** [comment]
By the way, the icons (still not sure about the left one, but the right one with `Zerocoin` text) look awesome!

**Comment by danimesq** [comment]
@imachug
> Thank you. Is there a repository for this site somewhere?

https://github.com/ZeroCoinOrganization/ZeroCoinOrganization.github.io
